config/routes.rb
Rails.application.routes.draw do
  resources :costs
  resources :incomes
  resources :categories

  root 'home#overview'

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  get 'overview', to: 'home#overview', as: :overview

  get 'statistic', to: 'home#statistic'

end

app/models/cost.rb
class Cost < ActiveRecord::Base
  belongs_to :category

  validates :category, presence: true

  validates :amount, presence: true, numericality: { only_integer: true }

  validate :check_total_cost

  private

  def check_total_cost
    errors.add(:amount, 'You spend too much') if (Cost.sum(:amount) + self.amount.to_i ) > Income.sum(:amount)
  end
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]

  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
  end

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(cost_params)

    respond_to do |format|
      if @cost.save
        format.html { redirect_to costs_url, notice: 'Cost was successfully created.' }
        format.json { render :show, status: :created, location: @cost }
      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to costs_url, notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      format.html { redirect_to costs_url, notice: 'Cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:cost).permit(:amount, :category_id)
    end
end

app/views/costs/_form.html.erb
<%= form_for @cost, :html => { :class => "form-horizontal cost", :style => 'text-align: left; font-size: 120%' } do |f| %>

    <% if @cost.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@cost.errors.count, "error") %> prohibited this cost from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @cost.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :amount, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :amount, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :category_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select("category_id", options_for_select(Category.all.map { |cate| [cate.name, cate.id]}),{}, {class: 'form-control'})%>
    </div>
  </div>

    <br>
    <br>


  <%= f.submit nil, :class => 'btn btn-primary', style: 'margin-right: 20px;' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            costs_path, :class => 'btn btn-default' %>

<% end %>

app/views/costs/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <%- model_class = Cost -%>
  <div class="page-header">
    <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
  </div>
  <%= render :partial => 'form' %>

</div>

app/views/costs/index.html.erb
<%- model_class = Cost -%>

<div class="page-header">
  <div class="col-md-8 pull-left" style="text-align: left">

    <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  </div>


  <div class="col-md-4 pull-right"  style="text-align: right">

    <%= link_to t('.new', :default => t("helpers.links.new")),
                new_cost_path,
                :class => 'btn btn-default ct-btn' %>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:category_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @costs.each do |cost| %>
      <tr>
        <td><%= link_to cost.id, cost_path(cost) %></td>
        <td><%= cost.amount %></td>
        <td><%= cost.category.name %></td>
        <td><%=l cost.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cost_path(cost), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cost_path(cost),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/costs/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <%- model_class = Cost -%>
  <div class="page-header">
    <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
  </div>
  <%= render :partial => 'form' %>
</div>

app/views/costs/show.html.erb
<%- model_class = Cost -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @cost.amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category_id) %>:</strong></dt>
  <dd><%= @cost.category_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              costs_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cost_path(@cost), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cost_path(@cost),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>