config/routes.rb
Rails.application.routes.draw do
  resources :costs
  resources :incomes
  resources :categories

  root 'home#overview'

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  get 'overview', to: 'home#overview', as: :overview

  get 'statistic', to: 'home#statistic'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@categories = Category.all		
  end

  def statistic
    @income = Income.where("created_at > ? ", DateTime.parse(params[:month_id])).sum(:amount)
    @cost = Cost.where("created_at > ? ", DateTime.parse(params[:month_id])).sum(:amount)

    respond_to do |format|
      format.js
    end
  end

  def overview
    cost_months = Cost.all.group_by { |m| m.created_at.beginning_of_month }.keys
    income_months = Income.all.group_by { |m| m.created_at.beginning_of_month }.keys

    @arraymonth = cost_months | income_months

    # convert to hash
    @hashmonth = { }
    (0..@arraymonth.length-1).each do |i|
      @hashmonth[@arraymonth[i]] = @arraymonth[i].strftime("%Y - %m")
    end
  end
end

app/views/home/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th>Total Incomes</th>
      <th>Total Cost</th>
      <th>NET</th>
    </tr>
  </thead>
  <tbody>    
    <% @categories.each do |category| %>
      <% incomes = 0 %>
      <% category.incomes.select(:amount).each { |a| incomes+=a.amount } %>
      <% costs = 0 %>
      <% category.costs.select(:amount).each { |a| costs+=a.amount } %>

      <tr>
        <td><%= link_to category.id, category_path(category) %></td>
        <td><%= category.name %></td>
        <td><%= incomes %></td>
        <td><%= costs %></td>
        <td style="color: <%= 'red' if (incomes < costs) %>">
          <%= incomes - costs %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/overview.html.erb
<div class="overviews">
  <h1 class="overview-title">OVERVIEW</h1>
  <div class="view-box overview-box">
    <div class="title">
      <li class="first-colum">Monthly overview</li>
      <li>
        <%= form_tag("/statistic", method: "get", remote: true) do %>
            <%= select_tag('month_id', options_from_collection_for_select(@hashmonth, 'first', 'last', '1' )) %>
            <%= button_tag 'Get', :name => nil, style: 'padding: 0px 25px; height: 50px; margin-left: 15px;' -%>
        <% end %>
      </li>
    </div>
    <br>
    <br>
    <div class="row">
      <div class="expences">
        <div class="col-md-6">Expenses</div>
        <div class="col-md-6" id="total-expense"></div>
      </div>
    </div>

    <div class="row">
      <div class="income">
        <div class="col-md-6">Income</div>
        <div id="total-income" class="col-md-6"></div>
      </div>
    </div>
  </div>
</div>

app/views/home/statistic.js.erb
$("#total-expense").html(<%= @cost %>);
$("#total-income").html(<%= @income %>);