config/routes.rb
Rails.application.routes.draw do
  resources :costs
  resources :incomes
  resources :categories

  root 'home#overview'

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  get 'overview', to: 'home#overview', as: :overview

  get 'statistic', to: 'home#statistic'

end

app/models/income.rb
class Income < ActiveRecord::Base
  belongs_to :category

  validates :amount, presence: true, numericality: { only_integer: true }

  validates :category, presence: true
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @income = Income.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to incomes_url, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to incomes_url, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_params
      params.require(:income).permit(:amount, :category_id)
    end
end

app/views/incomes/_form.html.erb
<%= form_for @income, :html => { :class => "form-horizontal income", :style => 'text-align: left; font-size: 120%' } do |f| %>

    <% if @income.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@income.errors.count, "error") %> prohibited this income from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @income.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :amount, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :amount, :class => 'form-control' %>
    </div>
    <%= error_span(@income[:amount]) %>
  </div>
  <div class="control-group">
    <%= f.label :category_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select("category_id", options_for_select(Category.all.map { |cate| [cate.name, cate.id]}),{}, {class: 'form-control'})%>
    </div>
    <%= error_span(@income[:category_id]) %>
  </div>


    <br>
    <br>

  <%= f.submit nil, :class => 'btn btn-primary', style: 'margin-right: 20px;' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            incomes_path, :class => 'btn btn-default' %>

<% end %>

app/views/incomes/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <%- model_class = Income -%>
  <div class="page-header">
    <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
  </div>
  <%= render :partial => 'form' %>
</div>

app/views/incomes/index.html.erb
<%- model_class = Income -%>

<div class="page-header">
  <div class="col-md-8 pull-left" style="text-align: left">
      <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  </div>


  <div class="col-md-4 pull-right"  style="text-align: right">

    <%= link_to t('.new', :default => t("helpers.links.new")),
                new_income_path,
                :class => 'btn btn-default ct-btn' %>
  </div>
</div>


<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:category_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <td><%= link_to income.id, income_path(income) %></td>
        <td><%= income.amount %></td>
        <td><%= income.category.name %></td>
        <td><%=l income.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_income_path(income), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      income_path(income),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/incomes/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <%- model_class = Income -%>
  <div class="page-header">
    <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
  </div>
  <%= render :partial => 'form' %>

</div>

app/views/incomes/show.html.erb
<%- model_class = Income -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @income.amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category_id) %>:</strong></dt>
  <dd><%= @income.category_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              incomes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_income_path(@income), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              income_path(@income),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>