config/routes.rb
Rails.application.routes.draw do
  resources :costs
  resources :incomes
  resources :categories

  root 'home#overview'

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  get 'overview', to: 'home#overview', as: :overview

  get 'statistic', to: 'home#statistic'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wallet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <!-- Fonts -->
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

  <%= csrf_meta_tags %>
</head>
<body>
<div id="content-wrapper">
  <div class="brand">Wallet</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
          <a class="navbar-brand" href="index.html">Business Casual</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to t('menu.overview'), overview_path %>
            </li>
            <li>
              <%= link_to t('menu.categories'), categories_path %>
            </li>
            <li>
              <%= link_to t('menu.costs'), costs_path %>
            </li>
            <li>
              <%= link_to t('menu.incomes'), incomes_path %>
            </li>

            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%= t('menu.languages.lang') %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to t('menu.languages.en'), change_locale_path(:en) %>
                </li>
                <li>
                  <%= link_to t('menu.languages.ru'), change_locale_path(:ru) %>
                </li>
              </ul>
            </li>

          </ul>

        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
    </nav>

  <div class="container">

    <div class="row">
      <div class="box">
        <div class="col-lg-12 text-center">

          <%= yield %>

        </div>
      </div>
    </div>

  </div>
</div>

  <!--<footer>-->
    <!--<div class="container">-->
      <!--<div class="row">-->
        <!--<div class="col-lg-12 text-center">-->
          <!--<p>Copyright &copy; Your Website 2014</p>-->
        <!--</div>-->
      <!--</div>-->
    <!--</div>-->
  <!--</footer>-->

</body>
</html>